#!/bin/bash
# =============================================================================
# Sub2API Helm Deployment Script
# =============================================================================
# Creates a local helm-values.yaml with fixed secrets when missing, then runs
# helm upgrade --install against deploy/helm/sub2api.
#
# Environment overrides:
#   RELEASE_NAME=sub2api
#   NAMESPACE=sub2api
#   CHART_DIR=/path/to/chart
#   VALUES_FILE=/path/to/helm-values.yaml
#   IMAGE_TAG=latest
#   DRY_RUN=true
#   HELM_BIN=helm
# =============================================================================

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

generate_secret() {
    openssl rand -hex 32
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RELEASE_NAME="${RELEASE_NAME:-sub2api}"
NAMESPACE="${NAMESPACE:-sub2api}"
CHART_DIR="${CHART_DIR:-${SCRIPT_DIR}/helm/sub2api}"
VALUES_FILE="${VALUES_FILE:-${SCRIPT_DIR}/helm-values.yaml}"
IMAGE_TAG="${IMAGE_TAG:-latest}"
DRY_RUN="${DRY_RUN:-false}"
CHART_NAME="sub2api"
HELM_BIN="${HELM_BIN:-helm}"

require_command() {
    local name="$1"
    if ! command_exists "$name"; then
        print_error "$name is not installed or not available in PATH."
        exit 1
    fi
}

create_values_file() {
    if [ -f "$VALUES_FILE" ]; then
        print_info "Using existing values file: $VALUES_FILE"
        return
    fi

    print_info "Creating values file with generated secrets: $VALUES_FILE"

    local jwt_secret
    local totp_encryption_key
    local admin_password
    local postgres_password
    local redis_password

    jwt_secret="$(generate_secret)"
    totp_encryption_key="$(generate_secret)"
    admin_password="$(generate_secret)"
    postgres_password="$(generate_secret)"
    redis_password="$(generate_secret)"

    cat > "$VALUES_FILE" <<EOF
# Generated by deploy/helm-deploy.sh.
# Keep this file private. It contains deployment secrets.

image:
  repository: weishaw/sub2api
  tag: ${IMAGE_TAG}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  hosts: []
  tls: []

persistence:
  enabled: true
  size: 10Gi

app:
  runMode: standard
  timezone: Asia/Shanghai
  adminEmail: admin@sub2api.local

secrets:
  app:
    jwtSecret: "${jwt_secret}"
    totpEncryptionKey: "${totp_encryption_key}"
    adminPassword: "${admin_password}"
    generateAdminPassword: false
  postgresql:
    password: "${postgres_password}"
  redis:
    password: "${redis_password}"
    generatePassword: false

postgresql:
  enabled: true
  auth:
    username: sub2api
    database: sub2api
  persistence:
    enabled: true
    size: 20Gi

redis:
  enabled: true
  persistence:
    enabled: true
    size: 8Gi
EOF

    chmod 600 "$VALUES_FILE" 2>/dev/null || true
    print_success "Generated $VALUES_FILE"
}

main() {
    require_command "$HELM_BIN"
    require_command openssl

    if [ ! -d "$CHART_DIR" ]; then
        print_error "Chart directory not found: $CHART_DIR"
        exit 1
    fi

    create_values_file

    print_info "Validating Helm chart..."
    "$HELM_BIN" lint "$CHART_DIR"

    local helm_args=(
        upgrade --install "$RELEASE_NAME" "$CHART_DIR"
        --namespace "$NAMESPACE"
        --create-namespace
        -f "$VALUES_FILE"
    )

    if [ "$DRY_RUN" = "true" ]; then
        helm_args+=(--dry-run)
    fi

    print_info "Running: ${HELM_BIN} ${helm_args[*]}"
    "$HELM_BIN" "${helm_args[@]}"

    print_success "Helm deployment command completed."
    echo ""
    local app_name
    if [[ "$RELEASE_NAME" == *"$CHART_NAME"* ]]; then
        app_name="$RELEASE_NAME"
    else
        app_name="${RELEASE_NAME}-${CHART_NAME}"
    fi

    echo "Access locally:"
    echo "  kubectl -n ${NAMESPACE} port-forward svc/${app_name} 8080:8080"
    echo ""
    echo "Admin password:"
    echo "  kubectl -n ${NAMESPACE} get secret ${app_name}-app -o jsonpath='{.data.admin-password}' | base64 -d"
}

main "$@"
